version: "3"
services:
  apache:
    build: .
    container_name: 'apache'
    ports:
      - "8092:80"
    links: 
      - mysql:mysql
  mysql:
    image: mysql
    container_name: 'mysql'
    volumes: 
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ipl 
      MYSQL_DATABASE: bdbn 
  phpmyadmin:
    image: phpmyadmin
    container_name: 'phpmyadmin'
    ports:
      - '9002:80'
volumes:
  mysql-data:
