---
# hosts : liste des hosts où le playbook s'appliquera
- hosts: localhost
  tasks:
# name : description de la tâche
    - name: "Install Apache Web Server"
# module ansible appelé (voir ansible modules)
      apt:
        name: apache2
        state: latest
    - name: "Install cowsay" 
      apt:
        name: cowsay
        state: latest
    - name: "Add alias"
      lineinfile:
       path: /home/examen/.bashrc
       state: present
       line: " drm='docker stop $(docker ps -aq) && docker rm $(docker ps -aq)' "
