---
# tasks file for deploy_nodejs_app_from_git_repo
- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: "git clone public repo"
  ansible.builtin.git:
    repo: "{{ repo_exoplanets }}"
    dest: "{{ localdir_exoplanets }}"


- name: "Build app"
  command: npm install
  args: 
    chdir: "{{ localdir_exoplanets }}"

- name: Install PM2
  npm:
    name: pm2
    global: yes

- name: Start App
  command: pm2 start npm -- start
  args:
      chdir:  "{{ localdir_exoplanets }}"

 
