---
# tasks file for exoplanets_reverseproxy
- name: "Install Apache"
  apt:
    update_cache: yes
    name: apache2
    state: present

- name: "Install openssl"
  apt:
    update_cache: yes
    name: openssl
    state: present

- name: "activate modules for reverse proxy and ssl"
  command: a2enmod ssl proxy proxy_http 
  notify: restart Apache

- name: set up key certificate
  template:
    src: "templates/apache.key"
    dest: "/etc/apache2/ssl/apache.key"

- name: set up certificate
  template:
    src: "templates/apache.crt"
    dest: "/etc/apache2/ssl/apache.crt"

- name: set up Apache virtualhost
  template:
    src: "templates/template_vhost.conf"
    dest: "/etc/apache2/sites-available/{{sitename}}_vhost.conf"

- name: enable new site
  command: "/usr/sbin/a2ensite {{sitename}}_vhost.conf"
  notify: reload Apache

- name: disable default Apache site
  ansible.builtin.command: "/usr/sbin/a2dissite 000-default.conf"
  notify: reload Apache
