---
# THIS PLAYBOOK MUST BE LAUNCHED IN ROOT !
# name of the playbook
- name: "Install Exoplanets(nodejs) site"
  # Install only on localhost machine
  hosts: localhost
  # Collect info on the system IP Adress, OS information, ....
  # performance cost !
  gather_facts: false
  vars:
    sitename: exoplanets
    repo_exoplanets : https://gitlab.vinci.be/olivier.choquet/exoplanets_infra.git
    localdir_exoplanets : /home/olivier/exoplanets_site
  roles: 
    - deploy_nodejs_app_from_git_repo
    - add_reverseproxy

  