version: "3"
services:
  apache:
    build: .
    container_name: 'apache'
    ports:
     - "8092:80"
    links: 
      - mysql:mysql
  mysql:
    image: mariadb:10.4
    container_name: 'mysql'
    volumes: 
      - mysql-data:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ipl 
      MYSQL_DATABASE: bdbn 
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: 'phpmyadmin'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '9002:80'
  adminer:
   image: adminer
   restart: always
   ports:
    - 9003:8080
volumes:
  mysql-data:
